name: releases

on: [ push ]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
          -   uses: actions/checkout@v4.1.1
          -   name: Upload zip
              uses: actions/upload-artifact@v1
              with:
                  name: Better-Ore-Visibility
                  path: pack/
